//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icebreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icebreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чат с {0}.
        /// </summary>
        public static string ChatWithMatchButtonText {
            get {
                return ResourceManager.GetString("ChatWithMatchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет%21.
        /// </summary>
        public static string ChatWithMessageGreeting {
            get {
                return ResourceManager.GetString("ChatWithMessageGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так. Повторить?.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы читаете это сообщение, значит  {0} добавил меня в **{1} команду.**.
        /// </summary>
        public static string InstallMessageKnownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я помогу вам познакомиться с большим количеством людей в вашей команде, случайным образом объединяя вас с кем-то новым с установленной периодичностью. У вас появится больше друзей, и вы узнаете о людях, с которыми работаете..
        /// </summary>
        public static string InstallMessageKnownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Оставайтесь на связи. В ближайшее время каждый получит сообщение от бота**.
        /// </summary>
        public static string InstallMessageKnownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы читаете это сообщение, значит  {0} добавил меня в **{1} команду.**.
        /// </summary>
        public static string InstallMessageUnknownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я помогу вам познакомиться с большим количеством людей в вашей команде, случайным образом объединяя вас с кем-то новым с установленной периодичностью. У вас появится больше друзей, и вы узнаете о людях, с которыми работаете..
        /// </summary>
        public static string InstallMessageUnknownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Оставайтесь на связи. В ближайшее время каждый получит сообщение от бота**.
        /// </summary>
        public static string InstallMessageUnknownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, я {0} в {1}. Бот, который каждый раз объединяет вас с новым коллегой. На этот раз вы общаетесь с {2}..
        /// </summary>
        public static string MatchUpCardContentPart1 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начните общаться в ближайшее время. Это просто!.
        /// </summary>
        public static string MatchUpCardContentPart2 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пообщайтесь с {0}..
        /// </summary>
        public static string MatchUpCardMatchedText {
            get {
                return ResourceManager.GetString("MatchUpCardMatchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время стать ближе!.
        /// </summary>
        public static string MatchUpCardTitleContent {
            get {
                return ResourceManager.GetString("MatchUpCardTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! На этот раз Icebreaker выбрал нас {0}. С радостью встречусь за чашкой кофе или просто поговорим..
        /// </summary>
        public static string MeetupContent {
            get {
                return ResourceManager.GetString("MeetupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} Встреча.
        /// </summary>
        public static string MeetupTitle {
            get {
                return ResourceManager.GetString("MeetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        public static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я всё вернул. В следующий раз вы получите рекомендацию для нового знакомства..
        /// </summary>
        public static string OptInConfirmation {
            get {
                return ResourceManager.GetString("OptInConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово! Бот поставлен на паузу. Чтобы возобновить, в любой момент нажмите здесь на кнопку «Вернуть Icebreaker».
        /// </summary>
        public static string OptOutConfirmation {
            get {
                return ResourceManager.GetString("OptOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приостановить Icebreaker.
        /// </summary>
        public static string PausePairingsButtonText {
            get {
                return ResourceManager.GetString("PausePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложить встречу.
        /// </summary>
        public static string ProposeMeetupButtonText {
            get {
                return ResourceManager.GetString("ProposeMeetupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуть Icebreaker.
        /// </summary>
        public static string ResumePairingsButtonText {
            get {
                return ResourceManager.GetString("ResumePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет!.
        /// </summary>
        public static string SalutationTitleText {
            get {
                return ResourceManager.GetString("SalutationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможности Icebreaker.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможности Icebreaker.
        /// </summary>
        public static string TourContentPageTitleText {
            get {
                return ResourceManager.GetString("TourContentPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделайте паузу. Отпуск? Командировка? Много работы? Нет проблем.
        ///Если вы какое-то время не хотите получать сообщения от чат-бота, это решается в один клик. .
        /// </summary>
        public static string TourMatchesBodyText {
            get {
                return ResourceManager.GetString("TourMatchesBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легко поставить на паузу, если нужно.
        /// </summary>
        public static string TourMatchesHeaderText {
            get {
                return ResourceManager.GetString("TourMatchesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время от времени я буду знакомить вас с кем-нибудь новым. 
        ///Если у вас есть желание, вы можете встретиться - пообедать или позвонить, если вы находитесь в разных местах. 
        ///Ждите от меня сообщения, в которых буду предлагать новых друзей..
        /// </summary>
        public static string TourWelcomeBodyText {
            get {
                return ResourceManager.GetString("TourWelcomeBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заводите новых друзей и стройте команду вместе.
        /// </summary>
        public static string TourWelcomeHeaderText {
            get {
                return ResourceManager.GetString("TourWelcomeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветственная картинка.
        /// </summary>
        public static string TourWelcomeImageAltText {
            get {
                return ResourceManager.GetString("TourWelcomeImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но я не могу обработать входящее сообщение. Тем не менее, вы можете узнать больше о моих возможностях..
        /// </summary>
        public static string UnrecognizedInput {
            get {
                return ResourceManager.GetString("UnrecognizedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможности Icebreaker.
        /// </summary>
        public static string WelcomeTourTitle {
            get {
                return ResourceManager.GetString("WelcomeTourTitle", resourceCulture);
            }
        }
    }
}
